databases:
  - name: gymbuds
    plan: free
    databaseName: gymbuds
    user: gymbuds

services:
  - type: web
    name: gymbuds
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gymbuds
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
